[package]
name = "charm"
version = "0.1.0"
authors = ["misson20000 <xenotoad@xenotoad.net>"]
edition = "2021"
default-run = "gtk"

[features]
default = ["gtk"]
gtk = ["dep:gtk"]

[dependencies]
gtk = { version = "0.8.2", optional = true, package = "gtk4" }
glib = "0.19.7"
futures = "0.3.30"
lazy_static = "1.4.0"
tokio = { version = "1.37.0", features = ["full"] }
hex-literal = "0.4.1"
send_wrapper = "0.6.0"
conv = "0.3.3"
parking_lot = "0.12.3"
imbl = "3.0.0"
enum_dispatch = "0.3.13"
byteorder = "1.5.0"
lru = "0.12.3"
take_mut = "0.2.2"
itertools = "0.13.0"
roxmltree = "0.20.0"
once_cell = "1.19.0"
arc-swap = "1.7.1"
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
seq-macro = "0.3.5"
rental = "0.5.6"
serde = "1.0.202"
serde_derive = "1.0.202"
bincode = "1.3.3"

[dev-dependencies]
pretty_assertions = "1.4.0"
assert_matches = "1.5"
rusty-fork = "0.3.0"

[[bin]]
name = "gtk"
required-features = ["gtk"]

[[bin]]
name = "layoutplayground"
