[package]
name = "charm"
version = "0.1.0"
authors = ["misson20000 <xenotoad@xenotoad.net>"]
edition = "2018"
default-run = "gtk"

[features]
default = ["gtk"]
gtk = ["dep:glib", "dep:gtk", "dep:gdk", "dep:gdk-pixbuf", "dep:gio", "dep:cairo-rs"]

[dependencies]
glib = { version = "0.15.12", optional = true }
gtk = { version = "0.15.5", features = ["v3_20"], optional = true }
gdk = { version = "0.15.4", optional = true }
gdk-pixbuf = { version = "0.15.11", optional = true }
gio = { version = "0.15.12", optional = true }
cairo-rs = {version = "0.15.12", optional = true }
futures = "0.3.21"
lazy_static = "1.4.0"
tokio = { version = "1.20.1", features = ["full"] }
hex-literal = "0.3.4"
send_wrapper = "0.6.0"
owning_ref = "0.4.1"
conv = "0.3.3"
parking_lot = "0.12.1"
imbl = { git = "https://github.com/jneem/imbl/" }
enum_dispatch = "0.3.8"
byteorder = "1.4.3"
lru = "0.7.8"
take_mut = "0.2.2"
itertools = "0.10.3"

[[bin]]
name = "gtk"
required-features = ["gtk"]

[dev-dependencies]
roxmltree = "0.14.1"
