[package]
name = "charm"
version = "0.1.0"
authors = ["misson20000 <xenotoad@xenotoad.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glib = "0.10.2"
gtk = { version = "0.9.2", features = ["v3_20"] }
gdk = "0.13.2"
gdk-pixbuf = "0.9.0"
gio = "0.9.1"
cairo-rs = "0.9.1"
ncurses = "5.99.0"
futures = "0.3.5"
lazy_static = "1.4.0"
tokio = { version = "0.2.22", features = ["full"] }
hex-literal = "0.3.1"
send_wrapper = "0.4.0"
owning_ref = "0.4.1"
conv = "0.3.3"
parking_lot = "0.11.1"
im = { git = "https://github.com/vorner/im-rs/", branch = "iter-clone" }
enum_dispatch = "0.3.3"
byteorder = "1.3.4"
lru = "0.6.1"
take_mut = "0.2.2"

[features]
default = []
test_listing = []
