[package]
name = "charm"
version = "0.1.0"
authors = ["misson20000 <xenotoad@xenotoad.net>"]
edition = "2021"
default-run = "gtk"

[features]
default = ["gtk"]
gtk = ["dep:gtk"]

[dependencies]
gtk = { version = "0.8.0", optional = true, package = "gtk4" }
futures = "0.3.30"
lazy_static = "1.4.0"
tokio = { version = "1.36.0", features = ["full"] }
hex-literal = "0.4.1"
send_wrapper = "0.6.0"
conv = "0.3.3"
parking_lot = "0.12.1"
imbl = "2.0.3"
enum_dispatch = "0.3.12"
byteorder = "1.5.0"
lru = "0.12.2"
take_mut = "0.2.2"
itertools = "0.12.1"
roxmltree = "0.19.0"
once_cell = "1.19.0"
arc-swap = "1.6.0"
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
seq-macro = "0.3.5"

[dev-dependencies]
pretty_assertions = "1.4.0"
assert_matches = "1.5"
rusty-fork = "0.3.0"

[[bin]]
name = "gtk"
required-features = ["gtk"]

[[bin]]
name = "layoutplayground"
