[package]
name = "charm"
version = "0.1.0"
authors = ["misson20000 <xenotoad@xenotoad.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glib = "0.15.12"
gtk = { version = "0.15.5", features = ["v3_20"] }
gdk = "0.15.4"
gdk-pixbuf = "0.15.11"
gio = "0.15.12"
cairo-rs = "0.15.12"
futures = "0.3.21"
lazy_static = "1.4.0"
tokio = { version = "1.20.1", features = ["full"] }
hex-literal = "0.3.4"
send_wrapper = "0.6.0"
owning_ref = "0.4.1"
conv = "0.3.3"
parking_lot = "0.12.1"
imbl = { git = "https://github.com/jneem/imbl/" }
enum_dispatch = "0.3.8"
byteorder = "1.4.3"
lru = "0.7.8"
take_mut = "0.2.2"

[features]
default = []
test_listing = []
