[package]
name = "charm"
version = "0.1.0"
authors = ["misson20000 <xenotoad@xenotoad.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glib = "0.9.3"
gtk = { version = "0.8.1", features = ["v3_20"], git = "https://github.com/misson20000/gtk/", branch = "0.8-workaround-985" }
gdk = "0.12.1"
gio = "0.8.1"
cairo-rs = "0.8.1"
ncurses = "5.99.0"
futures = "0.3.4"
lazy_static = "1.4.0"
tokio = { version = "0.2", features = ["full"] }
hex-literal = "0.2.1"
send_wrapper = "0.4.0"
owning_ref = "0.4.1"
conv = "0.3.3"

[features]
default = []
test_listing = []