[package]
name = "charm"
version = "0.1.0"
authors = ["misson20000 <xenotoad@xenotoad.net>"]
edition = "2018"
default-run = "gtk"

[features]
default = []
gtk = ["dep:gtk"]

[dependencies]
gtk = { version = "0.4.8", optional = true, package = "gtk4" }
futures = "0.3.24"
lazy_static = "1.4.0"
tokio = { version = "1.21.2", features = ["full"] }
hex-literal = "0.3.4"
send_wrapper = "0.6.0"
conv = "0.3.3"
parking_lot = "0.12.1"
imbl = { git = "https://github.com/jneem/imbl/" }
enum_dispatch = "0.3.8"
byteorder = "1.4.3"
lru = "0.8.1"
take_mut = "0.2.2"
itertools = "0.10.5"
roxmltree = "0.15.0"
once_cell = "1.15.0"
arc-swap = "1.5.1"
tracing = "0.1.37"
tracing-subscriber = "0.3.16"

[dev-dependencies]
pretty_assertions = "1.3.0"
assert_matches = "1.5"

[[bin]]
name = "gtk"
required-features = ["gtk"]

[[bin]]
name = "layoutplayground"
